Eduplus.Web/Controllers/AdmissionsController.cs
using Eduplus.DTO.AcademicModule;
using Eduplus.Services.Contracts;
using Rotativa;
using Rotativa.Options;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Eduplus.Web.Controllers
{

    public class AdmissionsController : BaseController
    {
        // GET: Addmissions
        private readonly IGeneralDutiesService _generalDuties;
        private readonly IStudentService _studentService;
        private readonly IArticleService _articleService;
        private readonly ICommunicationService _commService;
        private readonly IBursaryService _bursaryService;
        private readonly IAcademicAffairsService _academicAffairs;
        public AdmissionsController(IGeneralDutiesService generalDuties, IStudentService studentService,
            IArticleService articleService, ICommunicationService commService,IBursaryService bursaryService, IAcademicAffairsService academicService)
        {
            _generalDuties = generalDuties;
            _studentService = studentService;
            _articleService = articleService;
            _commService = commService;
            _bursaryService = bursaryService;
            _academicAffairs = academicService;

        }

        public ActionResult Instructions()
        {
            return View();
        }
        public ActionResult DegreeProgramme()
        {
            var progs = _generalDuties.AllProgrammesByFaculty();
            return View(progs);
        }
        
        public ActionResult Departments()
        {
            var depts = _generalDuties.AllAcademicDepartments();
            return View(depts);
        }
        public ActionResult View_Detail(string item)
        {
            var detail = _articleService.FetchFacultyArticle(item);
            return View(detail);
        }

        [AllowAnonymous]
        public JsonResult PopulateFaculty()
        {

            var faculties = _generalDuties.FetchFaculties().ToList();

            return this.Json(faculties, JsonRequestBehavior.AllowGet);
        } 
        [AllowAnonymous]
        public JsonResult PopulateDepartment(string _facultyCode)
        {
           
                var depts = _generalDuties.FetchDepartments(_facultyCode)
                            .OrderBy(a => a.Title).ToList();
                return this.Json(depts, JsonRequestBehavior.AllowGet);
           
        }
        [AllowAnonymous]
        public JsonResult PopulateCountry()
        {

            var depts =_generalDuties.FetchCountries();
                            //.OrderBy(a => a.Title).ToList();
                return this.Json(depts, JsonRequestBehavior.AllowGet);
          
        }
        [AllowAnonymous]
        public JsonResult PopulateState(string _country)
        {
            
                var depts = _generalDuties.FetchStates(_country);
                return this.Json(depts, JsonRequestBehavior.AllowGet);
           
        }

       
        [AllowAnonymous]
        public JsonResult PopulateLga(string _state)
        {
            
                var depts = _generalDuties.FetchLgs(_state);
                return this.Json(depts, JsonRequestBehavior.AllowGet);
           
        }
        #region ACADEMIC CALENDER
        [AllowAnonymous]
        public ActionResult AcademicCalender()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult CurrentAcademicCalender()
        {
            var calender = _academicAffairs.FetchCurrentCalender();

            return new ViewAsPdf(calender)
            {
                PageSize = Size.A4,
                PageOrientation=Orientation.Portrait,
                CustomSwitches = "--footer-right \"Date: [date] [time]\" " +
                        "--footer-center \"Page: [page] of [toPage]\" --footer-line --footer-font-size \"9\" --footer-spacing 5 --footer-font-name \"calibri light\"",
                PageMargins = { Left = 2, Right = 2, Top = 2, Bottom = 10 }
            };
        }
        #endregion



        [HttpGet]
        public ActionResult CurrentFeeSchedule()
        {
            
            return View();
        }
        [HttpGet]
        public ActionResult CurrentFeeSchedules(string faculty,string type)
        {
            var schedule = _bursaryService.FetchCurrentFeeSchedule(faculty,type);

            return new ViewAsPdf(schedule)
            {
                PageSize = Size.A4,
                PageOrientation = Orientation.Portrait,
                CustomSwitches = "--footer-right \"Date: [date] [time]\" " +
                        "--footer-center \"Page: [page] of [toPage]\" --footer-line --footer-font-size \"9\" --footer-spacing 5 --footer-font-name \"calibri light\"",
                PageMargins = { Left = 2, Right = 2, Top = 2, Bottom = 10 }
            };
        }

        #region FRESHMEN PROFILE CREATION
        [HttpGet]
        public ActionResult NewStudentProfile()
        {
            return View();
        }

        public int SubmitNewStudent(ProspectiveStudentDTO data)
        {
            int stat = 0;//some has taken your email
            
            string studentId;
            string mail = data.Email;
            string pasword = data.Password;
            string mailresponse;
            string fullname = data.Title + " " + data.Surname + ", " + data.Firstname + " " + data.MIddlename;
            stat = _studentService.CreateNewStudentProfile(data, out studentId);
            if (stat == 1)//send mail
            {
                string msgBody = "Your personal data profile was successfully created." + "\n" +
                "Login to the registration portal to complete your registration." + "\n" +
                "Your login details is as follows: " + "\n" +
                "Registration Number= " + studentId + "\n" + "Username= " + mail + "Password= " + pasword + "\n";
                mailresponse = _commService.SendMail(mail, msgBody,"Profile Creation");
                if (mailresponse == "Ok")
                {
                    stat=1;
                }
                return stat;

            }
            return stat;
        }

        public int SubmitNewStudent1(ProspectiveStudentDTO data)
        {
            int stat = 0;//some has taken your email

            string studentId;
            string mail = data.Email;
            string pasword = data.Password;
            //string mailresponse;
            string fullname = data.Title + " " + data.Surname + ", " + data.Firstname + " " + data.MIddlename;
            stat = _studentService.CreateNewStudentProfile(data, out studentId);
            if (stat == 1)//send mail
            {
                
                return stat;

            }
            return stat;
        }
        #endregion
        void PopulateFaculties()
        {

            var _faculties = _generalDuties.FetchFaculties().ToList();

            ViewBag.faculties=new SelectList(_faculties,"FacultyCode","Title");
        }
        private void ProgrameTypes()
        {
            List<string> st = new List<string> {
                "Degree",
                "Predegree"
            };


            ViewBag.ProgrammeType = new SelectList(st);
           
        }

        public JsonResult AllProgrammes()
        {
            return Json(_generalDuties.FetchProgrammes(), JsonRequestBehavior.AllowGet);
        }

    }
}

Eduplus.Web/Views/Shared/FooterPartial.cshtml
<style>
    .ul-me {
        list-style-type: none;
        padding-left:5px;
        margin-left:1px;
    }

        .ul-me li span {
            color: #ffffff;
        }
        .me-h5{
            margin-left:5px; 
            color:#f3d907; 
            font-weight:bold; 
            font-size:15px;
            text-underline-position:below;
            text-decoration-line:underline;
        }
</style>

<hr />
<div class="row">
    <div class="col-md-3">
        <h5 class="me-h5">ND Programmes</h5>
        <ul class="ul-me">

            <li><a href='@Url.Action("InfoView","Home",new { view = "English and Literary" })'><span style="color:#ffffff">Computer Science</span></a></li>
            <li><a href='@Url.Action("InfoView","Home",new { view = "Christian Religious Studies" })'><span>Computer Engineering</span></a></li>
            <li><a href='@Url.Action("InfoView","Home",new { view = "Christian Religious Studies" })'><span>Electrical/Electronics Engineering</span></a></li>
            <li><a href='@Url.Action("InfoView","Home",new { view = "Christian Religious Studies" })'><span>Public Administration</span></a></li>
            <li><a href='@Url.Action("InfoView","Home",new { view = "Christian Religious Studies" })'><span>Science Laboratory Technology</span></a></li>
        </ul>
    </div>
    <div class="col-md-3" style="padding:0px;">
        <h5 class="me-h5">Entrepreneurship Certificate Programmes</h5>
        <ul class="ul-me">

            <li><a href='@Url.Action("InfoView","Home",new { view = "Accounting" })'><span style="color:#ffffff">Microsoft Imagine Academy</span></a></li>
            <li><a href='@Url.Action("InfoView","Home",new { view = "Business Administration" })'><span>Information Communication Technology</span></a></li>
            <li><a href='@Url.Action("InfoView","Home",new { view = "Marketting" })'><span>Health Safety Environment</span></a></li>
            <li><a href='@Url.Action("InfoView","Home",new { view = "Public Administration" })'><span>Catering and Hotel Management</span></a></li>
            <li><a href='@Url.Action("InfoView","Home",new { view = "Public Administration" })'><span>Film Making</span></a></li>
            <li><a href='@Url.Action("InfoView","Home",new { view = "Public Administration" })'><span>Agriculture Training Programme</span></a></li>
            <li><a href='@Url.Action("InfoView","Home",new { view = "Public Administration" })'><span>Building and Facility Management</span></a></li>
            <li><a href='@Url.Action("InfoView","Home",new { view = "Public Administration" })'><span>Fashion and Design</span></a></li>
            <li><a href='@Url.Action("InfoView","Home",new { view = "Public Administration" })'><span>Shoe Making</span></a></li>
            <li><a href='@Url.Action("InfoView","Home",new { view = "Public Administration" })'><span>Cosmetology and Soap Making</span></a></li>
            <li><a href='@Url.Action("InfoView","Home",new { view = "Public Administration" })'><span>Entrepreneurship and Leadership Training</span></a></li>
             

        </ul>
    </div>
 </div>

<div class="row">
    <hr />
    <p style="text-align:right;">copy; @DateTime.Now.Year - JetKing University College, </p>
  
</div>
<hr/>

Eduplus.Web/Views/Shared/_A4ReportLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - Obong University</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    
    <div class="id" style="width:auto;margin-left:auto;margin-right:auto;margin-top:2px; 
overflow:hidden;">
        
            <div class="report-header">
                <img src="~/Content/images/LOGO.png" width="100" height="100"  />
                <br /><b style="font-family:'Arial Rounded MT';font-size:25px;font-weight:bold">
                Obong University, Obong Ntak</b>
                <br/><a style ="font-family:'Arial Rounded MT';font-size:14px;font-weight:bold">Etim Ekpo, Akwa Ibom State</a> 
            </div>
            
        
        
        <div class="container">
            @RenderBody()
        </div>

    </div>
    
</body>
</html>

Eduplus.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title-Eduplus</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
</head>
<body>
    <div class="wrapper">
        <img src="~/Content/images/jkbana.png" class="banner-image" />
        <p style="text-align:justify; float:right; display:block;">
            <b>
                Tel: +2348107381867<br />+2348027175638<br />+2348037847780
                <br />

            </b>
            <br />
        </p>
        <section>
            @Html.Partial("_MenuPartial")
        </section>
        
            <div class="row">
                <div class="col-md-8">
                    @Scripts.Render("~/bundles/jquery")
                    @Scripts.Render("~/bundles/bootstrap")
                    @Scripts.Render("~/bundles/menu")
                    @Scripts.Render("~/bundles/knockout")
                    @RenderSection("scripts", required: false)
                    @RenderBody()
                </div>
                <div class="col-md-4">
                    <section class="row">
                        @Html.Action("_NewsPartial", "Home")
                    </section>
                    <section class="row">
                        @Html.Action("_EventsPartial", "Home")
                    </section>
                </div>
               
            </div>

       
        <footer style="background-color:#ff6a00; color:#fff;">
           @Html.Action("FooterPartial","Home")
        </footer>
    </div>
    
   
</body>
</html>

Eduplus.Web/Views/Shared/_MenuPartial.cshtml
<div id='cssmenu'>
    <ul>
        <li><a href='@Url.Action("index","Home")'><span>Home</span></a></li>
        <li class='active has-sub'>
            <a href='#'><span>About</span></a>
            <ul>
                <li><a href='@Url.Action("InfoView","Home",new { view = "About Obong University" })'><span>Obong University</span></a></li>
                <li><a href='@Url.Action("InfoView","Home",new { view = "Mission" })'><span>Mission</span></a></li>
                <li><a href='@Url.Action("InfoView","Home",new { view = "Vision" })'><span>Vision</span></a></li>
                <li><a href='@Url.Action("InfoView","Home",new { view = "Philosophy" })'><span>Our Philosophy</span></a></li>

            </ul>
        </li>

        <li class='active has-sub'>
            <a href='#'><span>Study At JetKing University College</span></a>
            <ul>
                <li><a href='@Url.Action("InfoView","Home",new { view = "Undergraduate Programme" })'><span>Undergraduate Programme</span></a></li>
                
                <li class="active has-sub1">
                    <a href='#'><span>Faculties</span></a>
                    <ul style="margin-left:60px">
                        <li><a href='@Url.Action("CollegeDetail","Home",new { college = "Natural and Applied Sciences" })'><span>Faculty of Natural and Applied Sciences</span></a></li>
                        <li><a href='@Url.Action("CollegeDetail","Home",new { college = "Arts and Humanities" })'><span>Faculty of Arts and Humanities</span></a></li>
                        <li><a href='@Url.Action("CollegeDetail","Home",new { college = "Management Sciences" })'><span>Faculty of Management Sciences</span></a></li>
                        <li><a href='@Url.Action("CollegeDetail","Home",new { college = "Social Sciences" })'><span>Faculty of Social Sciences</span></a></li>
                    </ul>
                </li>

                <li><a href='@Url.Action("CurrentAcademicCalender","Admissions")'><span>Current Academic Calender</span></a></li>
                <li><a href='@Url.Action("CurrentFeeSchedule","Admissions")'><span>Current Fees</span></a></li>
                
            </ul>
        </li>
        <li><a href='@Url.Action("Instructions","Admissions")'><span>Apply for Addmission</span></a></li>
        <li class='last'><a href='#'><span>Contact Us</span></a></li>
        <li class='last'><a href='https://smc.jetkinguniversitycolleged.net'><span>Portal</span></a></li>


    </ul>

</div>