Eduplus.Web.SMC/ViewModels/AddStudentViewModel.cs
using Eduplos.Domain.CoreModule;
using Eduplos.DTO.CoreModule;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Eduplos.Web.SMC.ViewModels
{
    public class AddStudentViewModel
    {
        public StudentDTO student { get; set; }
        public int sessionId { get; set; }
    }
}

Eduplus.Web.SMC/Controllers/Admission_CenterController.cs
using Eduplos.Domain.AcademicModule;
using Eduplos.Domain.CoreModule;
using Eduplos.DTO.AcademicModule;
using Eduplos.DTO.CoreModule;
using Eduplos.eb.SMC.ViewModels;
using Eduplos.Services.Contracts;
using Eduplos.Web.SMC.PDFGenerations;
using Eduplos.Web.SMC.ViewModels;
using KS.AES256Encryption;
using KS.Services.Contract;
using KS.Web.Security;
using OfficeOpenXml;
using QRCoder;
using Rotativa;
using Rotativa.Options;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Caching;
using System.Web.Http.Results;
using System.Web.Mvc;

namespace Eduplos.Web.SMC.Controllers
{
   // [KSWebAuthorisation]
    public class Admission_CenterController : BaseController
    {
        // GET: Pre_Admission_Center
        private readonly IGeneralDutiesService _generalDuties;
        private readonly IStudentService _studentService;
        private readonly ICommunicationService _commService;
        private readonly IBursaryService _bursaryService;
        private readonly IStudentsAccountsService _studentAccount;
        private readonly IUserService _userService;

        public Admission_CenterController(IStudentService studentService, IGeneralDutiesService generalDuties, ICommunicationService commService,
            IStudentsAccountsService aService, IBursaryService bursaryService, IUserService use)
        {
            _studentService = studentService;
            _generalDuties = generalDuties;
            _commService = commService;
            _bursaryService = bursaryService;
            _studentAccount = aService;
            _userService = use;
        }

        #region ALLOWED ADMISSION FOR PROSPECTIVES
       
        public ActionResult NewStudentProfile()
        {
            return View();
        }
        public int SubmitNewStudentProfile(ProspectiveStudentDTO data)
        {
            int stat = 0;//some has taken your email
            
            stat = _studentService.CreateNewStudentProfile(data);
            if (stat == 1)//send mail
            {
                
                return stat;

            }
            else
            return stat;
        }
        
        #endregion
        #region PROSPECTIVE STUDENTS FROM SCRATCH
        [KSWebAuthorisation]
        public ActionResult PayAdmissionFee()
        {
            var adminSesion = _generalDuties.FetchAdmissionSession().FirstOrDefault();
            
            var user = (CustomPrincipal)Session["LoggedUser"];

            //Check if Invoice Already exist
            var inv = _studentAccount.CheckAdmissionFeePayment(user.UserId);
            string flag;
            switch(inv)
            {
                case 0:
                    
                    var invoice = _studentAccount.GenerateStudentPaymentInvoice(user.UserId, "Screening Fee",adminSesion.SessionId, User.UserId, out flag);
                    if(flag!="Ok")
                    {
                        ViewBag.msg = flag;
                        return View("PaymentInvoice", "Payments", new { transId = invoice.TransactionId });
                    }
                    else
                    {
                        return RedirectToAction("PaymentInvoice", "Payments", new { transId = invoice.TransactionId });
                    }                  
                case 1:
                    return RedirectToAction("MyInvoices", "Payments");
                default:
                    return RedirectToAction("Prospectives");
            }
            
        }
        [KSWebAuthorisation]
        public ActionResult PayAcceptanceFee()
        {
            var currentSesion = _generalDuties.FetchCurrentSemester();
             
            var student = _studentService.FetchStudent(User.UserId);
            var session = _generalDuties.FetchSessions().Where(s => s.Title == student.YearAdmitted).FirstOrDefault();
            //Check if Invoice Already exist
            var inv = _studentAccount.CheckAcceptanceFeePayment(User.UserId);
            var _userData = _generalDuties.GetProgrammeTypes().Where(a=>a.Type==student.ProgrammeType).SingleOrDefault();
            string flag;
            switch (inv)
            {
                case 0:
                    if(_userData.CollectAcceptanceFee==true)
                    {
                        var invoice = _studentAccount.GenerateStudentPaymentInvoice(student.StudentId, "Acceptance Fee", session.SessionId, User.UserId, out flag);
                        if (flag != "Ok")
                        {
                            ViewBag.msg = flag;
                            return View();
                        }
                        else
                        {
                            return RedirectToAction("PaymentInvoice", "Payments", new { transId = invoice.TransactionId });
                        }
                    }
                    else //AdmitStudent
                    {
                        var ck=_studentService.AddmitWithoutAcceptanceFee(User.UserId);
                        _userService.ChangeUserRole(User.UserId, User.UserId, "Prospective", "Student");
                        //Send Student Matricnumber
                        string msg="Congratulations! Your admission has been accepted into this noble institution, please go ahead and pay stipulated fees."+"\n"+
                            "Your new RegNo is= "+ck+"\n"+"Note: If your new RegNo is contained in this mail, use it as your new username, else maintain your old username in the portal"+"\n"+ " Thank you";
                       // _commService.SendMail(student.Email, msg, "Admission Acceptance");
                        return RedirectToAction("Login", "Accounts"); ;
                    }
                    
                case 1:
                    return RedirectToAction("MyInvoices", "Payments");
                default:
                    return RedirectToAction("Prospectives");
            }

        }


        #endregion

        [KSWebAuthorisation]
        [HttpGet]
        public ActionResult AddStudent()
        {

            return View();
        }
        
        [KSWebAuthorisation]
        public string SubmitNewStudent(AddStudentViewModel data)
        {
            Student st = new Student();
            
            st.Country = data.student.Country;
            st.BDay= data.student.BDay;
            st.BMonth = data.student.BMonth;
            st.BYear = data.student.BYear;
            st.DepartmentCode = data.student.DepartmentCode;
            st.Email = data.student.Email;
            st.EntryMode = data.student.EntryMode;
            st.Firstname = data.student.Firstname;
            st.Duration = data.student.Duration;
            st.MatricNumber = data.student.MatricNumber;
            st.kinAddress = data.student.KinAddress;
            st.KinMail = data.student.KinMail;
            st.Phone = data.student.Phone;
            st.ProgrammeCode = data.student.ProgrammeCode;
            st.ProgrammeType = data.student.ProgrammeType;
            st.Referee = data.student.Referee;
            st.RefereeAddress = data.student.RefereeAddress;
            st.RefereeMail = data.student.RefereeMail;
            st.RefereePhone = data.student.RefereePhone;
            st.Relationship = data.student.Relationship;
            st.ResidentialAddress = data.student.ResidentialAddress;
            st.Sex = data.student.Sex;
            st.State = data.student.State;
            st.Surname = data.student.Surname;
            st.Title = data.student.Title;
            st.Lg = data.student.Lg;
            st.MaritalStatus = data.student.MaritalStatus;
            st.Duration = data.student.Duration;
            st.CurrentLevel = data.student.CurrentLevel;
             
            var msg = _studentService.NewStudent(st, data.sessionId, User.UserId);
            
            return msg;

        }
        #region APPLICANTS OPERATIONS
        [KSWebAuthorisation]
        public ActionResult Prospectives()
        {

            //Check Current admission step
            var user = (CustomPrincipal)Session["LoggedUser"];
            var student = _studentService.FetchStudent(User.UserId);
            var userData = _generalDuties.GetProgrammeTypes().Where(a=>a.Type==student.ProgrammeType).FirstOrDefault();
             
            if(student.AddmissionCompleteStage==0)
            {
                ViewBag.stat = 0;
                return View();
            }
            if (student.AddmissionCompleteStage == 1)
            {
                return RedirectToAction("Addmissions_Step1");
                
            }
            if (student.AddmissionCompleteStage == 5 && string.IsNullOrEmpty(student.StudyMode))
            {
                return RedirectToAction("Addmissions_Step1");

            }
            if (student.AddmissionCompleteStage == 2 && userData.AdmissionPause>2)
            {
                return RedirectToAction("UploadPassport");

            }
            if (student.AddmissionCompleteStage == 3 && userData.AdmissionPause > 3)
            {
                return RedirectToAction("OlevelResults");

            }
            if (student.AddmissionCompleteStage == 4 && userData.AdmissionPause > 4)
            {
                return RedirectToAction("JambScore");

            }
            if (student.AddmissionCompleteStage == 5 && userData.AdmissionPause > 5)
            {
                return RedirectToAction("Addmissions_Step5");

            }
            if (student.AdmissionStatus == "Admitted")
            {
                ViewBag.stat = 3;
                return View();

            }
            else
            {
                ViewBag.stat = 4;
                return View();
            }
             
        }
        [KSWebAuthorisation]
        public JsonResult GetStudentStep1(string studentId)
        {
            string id;
            if (string.IsNullOrEmpty(studentId))

Eduplus.Web.SMC/Views/Admission_Center/AddStudent.cshtml
@{Layout = "~/Views/Shared/_Layout.cshtml";}
@{
    ViewBag.Title = "Add Student";
}


<div class="col-md-6">

    <div class="form-horizontal">

        <h3 style="color:#08581b">Admit New Student</h3>
        <hr />
        <div class="form-group">

            <div class="col-md-3">
                <select data-bind="value:Title, options:Titles, optionsCaption:'Your Title'" class="form-control"></select>
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-12">
                <input type="text" data-bind="value: Surname" class="form-control" placeholder="Surname" />
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-12">
                <input type="text" data-bind="value:Firstname" class="form-control" placeholder="First name" />

            </div>
        </div>
        <div class="form-group">

            <div class="col-md-12">
                <input type="text" data-bind="value:Middlename" class="form-control" placeholder="Middle name" />
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-4">
                <select data-bind="value:MaritalStatus, options:MStatus, optionsCaption:'Your marital status'" class="form-control"></select>
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-3">
                <select data-bind="value:Sex, options:Sexes, optionsCaption:'I am...'" class="form-control"></select>
            </div>
        </div>

        <div class="form-group">

            <div class="col-md-12">
                <input type="text" data-bind="value:ResidentialAddress" class="form-control" placeholder="Residential Address" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3">
                <select data-bind="value:Country, options:Countries,optionsValue:'Country', optionsCaption:'Select your Country'" class="form-control"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3">
                <select data-bind="value:State, options:States,optionsValue:'State', optionsCaption:'Select your State'" class="form-control"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <select data-bind="value:Lg, options:Lgs, optionsValue:'Lga', optionsCaption:'Select your lga'" class="form-control"></select>
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-12">
                <input type="email" data-bind="value:Email" class="form-control" placeholder="Email Address" />
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-10">
                <input type="tel" data-bind="value:Phone" class="form-control" placeholder="Phone number" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2">
                Birth Date
            </div>

            <div class="col-md-2">
                <select data-bind="value:BDay,options:days, optionsCaption:'Day'" class="form-control"></select>
            </div>
            <div class="col-md-3">
                <select data-bind="value:BMonth,options:months, optionsCaption:'-Month-'" class="form-control"></select>
            </div>
            <div class="col-md-3">
                <select data-bind="value:BYear,options:yrs, optionsCaption:'-Year-'" class="form-control"></select>
            </div>
        </div>

        <hr />
        <h4><label class="label label-success">Sponsor Information</label></h4>
        <div class="form-group">

            <div class="col-md-12">
                <input type="text" data-bind="value:NextKin" class="form-control" placeholder="Sponsor" />
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-12">
                <input type="text" data-bind="value:KinMail" class="form-control" placeholder="Sponsor Email" />
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-12">
                <input type="tel" data-bind="value:KinPhone" class="form-control" placeholder="Sponsor Phone Number" />
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-12">
                <input type="text" data-bind="value:KinAddress" class="form-control" placeholder="Sponsor's Address" />
            </div>
        </div>
        <hr />
        <h4><label class="label label-success">Referee's Information</label></h4>
        <div class="form-group">

            <div class="col-md-12">
                <input type="text" data-bind="value:Referee" class="form-control" placeholder="Referee full Name" />
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-12">
                <input type="text" data-bind="value:RefereeMail" class="form-control" placeholder="Referee Email" />
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-12">
                <input type="tel" data-bind="value:RefereePhone" class="form-control" placeholder="Referee Phone Number" />
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-12">
                <input type="tel" data-bind="value:RefereeAddress" class="form-control" placeholder="Referee's Address" />
            </div>
        </div>

        <h4><label class="label label-success">Academics</label></h4>
        <div class="form-group">

            <div class="col-md-12">
                <input type="text" data-bind="value:JambRegNumber" class="form-control" placeholder="Jamb Reg. Number" />
            </div>
        </div>

        <div class="form-group">

            <div class="col-md-12">
                <select data-bind="value:SessionId, options:sessions,optionsValue:'SessionId',optionsText:'Title', optionsCaption:'Admitted Session'" class="form-control"></select>
            </div>


        </div>

        <div class="form-group">

            <div class="col-md-12">
                <select data-bind="value:EntryMode, options:EntryModes, optionsCaption:'Mode of Entry'" class="form-control"></select>
            </div>


        </div>


        <div class="form-group">

            <div class="col-md-12">
                <select data-bind="value:FacultyCode, options:Faculties, optionsValue:'FacultyCode', optionsText:'Faculty', optionsCaption:'Select Faculty'" class="form-control"></select>
            </div>


        </div>
        <div class="form-group">

            <div class="col-md-12">
                <select data-bind="value:DepartmentCode, options:Departments, optionsValue:'DepartmentCode', optionsText:'Title', optionsCaption:'Select Department'" class="form-control"></select>
            </div>

        </div>
        <div class="form-group">

            <div class="col-md-12">
                <select data-bind="value:ProgrammeCode, options:Programmes, optionsValue:'ProgrammeCode', optionsText:'Fullname', optionsCaption:'Select Programme'" class="form-control"></select>
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-12">
                <select data-bind="value:ProgrammeType, options:Types, optionsCaption:'Programme Type'" class="form-control"></select>
            </div>
        </div>

        <div class="form-group">

            <div class="col-md-12">
                <select data-bind="value:CurrentLevel, options:Levels, optionsCaption:'Level'" class="form-control"></select>
            </div>

        </div>
        <div class="form-group">

            <div class="col-md-12">
                <select data-bind="value:Duration, options:durations, optionsCaption:'Study Duration'" class="form-control"></select>
            </div>

        </div>
        <div class="form-group">
            <button data-bind="click:submit, disabled:Kill" class="btn btn-success">Submit</button>
        </div>

    </div>
</div>

<div data-bind="loadingWhen: isLoading"></div>


@Scripts.Render("~/Scripts/ViewModels/addStudentVM.js")

<style>
    .validationMessage {
        color: red;
        font-size: 1.0em;
    }
</style>

Eduplus.Web.SMC/Views/Admission_Center/Addmissions_Step5.cshtml
@model Eduplos.Domain.CoreModule.StudentDocuments
@{
    ViewBag.Title = "Upload documents";
     
}

<h2>Upload your Document</h2>

@using (Html.BeginForm("Addmissions_Step5", "Admission_Center", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{
    <h3>
        Please combine all your credentials into a single PDF file  before uploading.</h3>
        <input type="File" accept="pdf/*" name="file" id="file" value="Choose File" />
        <div class="form-group">
            <button type="submit">Upload</button>
        </div>
}

Eduplus.Web.SMC/Views/Admission_Center/AlevelResults.cshtml
@{
    ViewBag.Title = "Jamb Subject Combination";

}

<div class="form-horizontal">
 
    <div id="sitting-1" style="width:80%;">
        <table class="table">
            <thead>
                <tr><th>From</th><th>To</th><th>Institution</th><th>Certificate Obtained</th></tr>
            </thead>
            <tbody data-bind="foreach:list">
                <tr>

                    <td data-bind="text:StartMonth"></td>
                    <td data-bind="text:EndMonth"></td>
                    <td data-bind="text:Institution"></td>
                    <td data-bind="text:Qualification"></td>
                    <td><button class="btn btn-danger" data-bind="click:$root.removeSubject">Delete</button></td>


                </tr>

            </tbody>
            <tfoot>
                 
                <tr>
                    <td><input type="text" data-bind="value:StartMonth" class="form-control" placeholder="e.g Sept, 1999"/></td>
                    <td><input type="text" data-bind="value:EndMonth" class="form-control" placeholder="e.g Sept, 1999" /></td>
                    <td><input type="text" data-bind="value:Institution" class="form-control" placeholder="Name of institution" /></td>
                    <td><input type="text" data-bind="value:Qualification" class="form-control" placeholder="Qualification obtained" /></td>
                    <td><button class="btn btn-info" data-bind="click:addSubject">+Add</button></td>

                </tr>
            </tfoot>
        </table>
    </div>

    <div class="form-group">
        <button data-bind="click:next, disabled:kill" class="btn btn-success">Done</button>
        <img src="~/Content/images/wait24.gif" data-bind="visible:kill" alt=""/>
    </div>
</div>

@section Scripts{
    @Scripts.Render("~/Scripts/ViewModels/alevelVM.js")
}
<style>
    .validationMessage {
        color: red;
        font-size: 1.0em;
    }
</style>

Eduplus.Web.SMC/Views/Admission_Center/ChooseProgramme.cshtml
<!DOCTYPE html>
@{ Layout = null;}
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Select Programme - @UserData.InstitutionName</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/vertical-menu.css" rel="stylesheet" />
</head>
<body>
    <div class="container-fluid" style="padding:0px 0px;">
        <p style="text-align:center">
            @if (UserData.Logo != null)
            {
                var base64 = Convert.ToBase64String(UserData.Logo);
                var imgSrc = String.Format("data:image/jpeg;base64,{0}", base64);
                <img src='@imgSrc' style="width:100px; height:100px;" />

            }
            <h3 style="text-align:center; border-top:solid; border:0px 2px 0px 2px; border-color:#0e983b;
                            color:#08581b;">
                @UserData.InstitutionName Addmissions Management Centre
            </h3>
        </p>
        <div class="row">

            <div id="hj" style="background-color:#119d43; height:20px;">
            </div>
            <div id="hkj" style="background-color:#0e983b;height:25px;">
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                
            </div>
            <div class="col-md-6">
                <h4>Select the programme type you wish to apply for and click on the 'Proceed button'</h4>
                @using (Html.BeginForm("ChooseProgramme", "Admission_Center", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    <div class="form-group">
                        @Html.Label("Choose Programme Type", new { @class = "form control" })
                    </div>
                    <div class="form-group">
                        @Html.DropDownList("types", null, new { @class = "form-control" })
                    </div>


                    <div class="form-group">
                        <input type="submit" class="btn btn-success btn-block" value="Proceed" />
                    </div>

                }
            </div>
            <div class="col-md-3">
               
            </div>

        </div>

        <footer style="background-color:#0a5e23; color:#fff;">
            For support/Enquiries
            <p>&copy; @DateTime.Now.Year - Akwa Ibom State College of Education, Afaha Nsit IT Directorate</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/knockout")
    
</body>
</html>

Eduplus.Web.SMC/Views/Admission_Center/FindStudent.cshtml
@{
    ViewBag.Title = "Find Student";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <h3>Find Student</h3>
    <hr />
    <div class="form-group">
        <div class="col-md-3">
            <input type="text" data-bind="value:searchString" class="form-control" placeholder="Reg/MatricNumber,Jamb No OR Surname"/>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3">
            <button class="btn btn-success" data-bind="click:$root.find">Search</button>
        </div>
    </div>
</div>

Eduplus.Web.SMC/Views/Admission_Center/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ProspectiveLayout.cshtml";
}

<h2>Index</h2>

Eduplus.Web.SMC/Views/Admission_Center/OlevelResults.cshtml
@{
    ViewBag.Title = "Olevel Results";
     
}

    <div class="form-horizontal">
        
        
        <div class="form-horizontal">
            <h3 style="background-color:#14c368;color:#ffffff; text-align:center">
               Sit Attempt <span data-bind="text:SitAttempt"></span>
            </h3> 
                <div class="form-group">

                    <div class="col-md-6">
                        
                        <select data-bind="value:ExamType, options:$root.examTypes, optionsCaption:'Select Exam Type'" class="form-control"></select>
                    </div>
                </div>
            <div class="form-group">

                <div class="col-md-6">
                    <input type="number" data-bind="value:ExamYear" class="form-control" placeholder="Exam Year" />
                </div>
            </div>
            <div class="form-group">

                <div class="col-md-6">
                    <input type="text" data-bind="value:ExamNumber" class="form-control" placeholder="Registration Number" />
                </div>
            </div>
            <div class="form-group">

                <div class="col-md-12">
                    <input type="text" data-bind="value:Venue" class="form-control" placeholder="Venue" />
                </div>
            </div>
            <div class="form-group">

                <div class="col-md-12">
                    <input type="hidden" data-bind="value:SitAttempt" />
                </div>
            </div>
            <h4>Results</h4>
            <div id="sitting-1" style="width:60%;">
                <table class="table">
                    <tr>
                        <th>
                            Subject
                        </th>
                        <th>Grade</th>
                        <th></th>
                    </tr>
                    <tbody data-bind="foreach:Details">
                       
                        <tr>
                            <td data-bind="text:Subject"></td>
                            <td data-bind="text:Grade"></td>
                            <td><button class="btn btn-danger" data-bind="click:$root.removeSubject">Delete</button></td>
                        </tr>
                        
                    </tbody>
                    <tfoot>
                        <tr>
                            <td><select data-bind="value:subject,options:Subjects,optionsValue:'Title',optionsText:'Title',optionsCaption:'Select Subject'" class="form-control" /></td>
                            <td><select data-bind="value:grade, options:Grades, optionsCaption:'Select Grade'" class="form-control" /></td>
                            <td><button class="btn btn-info" data-bind="click:addSubject,disable:kill">+Add</button>

                                <img src="~/Content/images/wait24trans.gif" data-bind="visible:kill"/> </td>
                        </tr>
                    </tfoot>
                </table>

            </div> 

        </div>
        
        
        <div class="row">
            <div class="col-md-4">
                <button data-bind="click:addsitting" class="btn btn-info">Add 2nd O/Level Sitting</button>
            </div>
            <div class="col-md-4">

            </div>
            <div class="col-md-4">
                <button data-bind="click:skip" class="btn btn-danger">Next</button>
            </div>
        </div>
     
</div>
    

@section Scripts{
    @Scripts.Render("~/Scripts/ViewModels/olevelResultsVM.js")
    }

Eduplus.Web.SMC/Views/Admission_Center/UploadManualMatricNumbers.cshtml
@{
    ViewBag.Title = "Upload Manual Matricnumbers";
    <!--Layout = "~/Views/Shared/_Layout.cshtml"; -->

}


@using (Html.BeginForm("UploadManualMatricNumbers", "Admission_Center", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{


    <div class="row">
        <div class="col-md-7">
           
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <div class="form-group">
                <input type="text" id="progType" name="progType" class="form-control" placeholder="Enter programme type: Degree Or NCE" />
                <input type="file" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" name="file" id="file" value="Choose File" />
            </div>


            <div class="form-group">
                <input type="submit" class="btn btn-block btn-success" value="Upload and Continue" />
            </div>

            <div class="form-group">
                @Html.ActionLink("Cancel", "Index", "Home")
            </div>
        </div>
    </div>
}
 

Eduplus.Web.SMC/Views/Admission_Center/UploadPassport.cshtml
@{
    ViewBag.Title = "Upload passport";
     
}


@using (Html.BeginForm("UploadPassport", "Admission_Center", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{
   

    <div class="row">
        <div class="col-md-7">
            <h3 style="color:#08581b">Upload Your Passport</h3>
            <hr/>
            <h4>Maximum passport size is 50Kb</h4>
            @Html.AntiForgeryToken();
            @Html.ValidationSummary(true);

            @if (ViewBag.foto != null)
                {
                 
                    var base64 = Convert.ToBase64String(@ViewBag.foto);
                    var imgSrc = String.Format("data:image/jpeg;base64,{0}", base64);
                    <img src='@imgSrc' style="max-width:200px; max-height:200px;border-radius:360px;" />
         
            }




            <div class="form-group">
                <img id="output" style="max-height:200px; max-width:200px;" />
                <input type="file" accept="image/*" onchange="loadfile(event)" name="image" id="image" value="Choose File" /> 
            </div>

            <div class="form-group">
                <input type="submit" class="btn btn-block btn-success" value="Upload and Continue"/>
            </div>

            <div class="form-group">
                @Html.ActionLink("Skip","OlevelResults","Admission_Center")
            </div>
        </div>
    </div>
}
<script>
    var loadfile = function (event) {

        var output = document.getElementById('output');
        output.src = URL.createObjectURL(event.target.files[0]);
    };

</script>