Eduplus.Web.SMC/Controllers/BursaryController.cs
using Eduplos.Domain.BurseryModule;
using Eduplos.DTO.BursaryModule;
using Eduplos.Services.Contracts;
using KS.Domain.AccountsModule;
using KS.Services.Contract;
using KS.UI.ViewModel;
using KS.Web.Security;
using Newtonsoft.Json;
using OfficeOpenXml;
using Rotativa;
using Rotativa.Options;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Eduplos.Web.SMC.Controllers
{
    [KSWebAuthorisation]
    public class BursaryController : BaseController
    {
        private readonly IBursaryService _bursaryService;
        private readonly IAccountsService _accountsService;
        private readonly IStudentsAccountsService _studentAccounts;
        private readonly IGeneralDutiesService _generalDuties;
        public BursaryController(IAccountsService accountsService,IBursaryService bursaryService,IStudentsAccountsService studentsAccounts,
            IGeneralDutiesService generalDuties)
        {
            _accountsService = accountsService;
            _bursaryService = bursaryService;
            _studentAccounts = studentsAccounts;
            _generalDuties = generalDuties;
        }
        public ActionResult Accounts()
        {
            return View();
        }

        public JsonResult AccountsList()
        {
            var accts = _accountsService.AllAccounts();
            return this.Json(accts, JsonRequestBehavior.AllowGet);
        }

        public Accounts SaveAccount(Accounts account)
        {
            var accounts = _accountsService.SaveAccount(account, User.UserId);
            return accounts;
        }

        public ActionResult AccountGroups()
        {
            return View();
        }

        
        #region FEESCHEDULE OPERATIONS
        public ActionResult FeeSchedules()
        {
            return View();
        }
        public JsonResult AllFeeSchedules()
        {
            var schedules = _bursaryService.FetchFeeSchedules();
            return this.Json(schedules, JsonRequestBehavior.AllowGet);
        }
        public ActionResult AddFeeSchedule()
        {
            return View();
        }
        
        public string AddFeeScheduleLine(FeeScheduleDetailsDTO scheduleLine)
        {
            string msg;
            var fee=_bursaryService.SaveFeeScheduleLineItem(scheduleLine,out msg,User.UserId);
            if (msg == "Ok")
                return JsonConvert.SerializeObject(fee);
            else return null;

        }
        public JsonResult ScheduleDetail(int scheduleId)
        {
            var fee = _bursaryService.FetchFeeScheduleById(scheduleId);

            return Json(fee,JsonRequestBehavior.AllowGet);
        }
        public string ApplySessionFeeSchedule(int scheduleId)
        {
            string msg = _bursaryService.ApplyFeeSchedule(scheduleId, User.UserId);
            return msg;
        }
        public string DeleteFeeScheduleLineItem(FeeScheduleDetailsDTO scheduleLine)
        {
            return _bursaryService.DeletefeeScheduleLineItem(scheduleLine, User.UserId);
        }

        #endregion

        #region STUDENT'S FEE OPERATIONS-BURSARY

        public JsonResult FetchStudentInvoice(string invoiceNo)
        {
            return Json(_studentAccounts.GetStudentPaymentInvoice(invoiceNo), JsonRequestBehavior.AllowGet);
        }
       

        [HttpGet]
        public ActionResult StudentAccount()
        {
            return View();
        }

        public JsonResult FetchStudentAccount(string matricNumber)
        {
            
            var student =_bursaryService.StudentAccountSummary(matricNumber.ToUpper());
           
            return Json(student, JsonRequestBehavior.AllowGet);
        }

        public ViewResult DebitStudentAccount(string studentId)
        {
            return View();
        }
        public string SaveStudentDebit(TransactionDTO viewModel)
        {
            
            return _bursaryService.DebitStudentAccount(viewModel, User.UserId);
        }

        public ActionResult CreditStudent(string studentId )
        {
            return View();
        }
        public string SaveStudentCredit(TransactionDTO viewModel)
        {
            outPutMsg result = new outPutMsg();

            string msg="";
            var tc=_studentAccounts.GenerateStudentInvoiceToCreditStudentAccount(viewModel, User.UserId,out msg);
            result.message = msg;
            if (msg != "Ok")
            {
                result.message = msg;
                result.status = 0;
            }
            else
            {
                result.value = tc;
                result.status = 1;
            }
            var chk = JsonConvert.SerializeObject(result);
            return chk;
        }

        public ActionResult StudentAccountsDetail(string studentId=null)
        {
            string _regNo;
            if (!string.IsNullOrEmpty(studentId))
            {
                _regNo = studentId;
            }
            else
            {
                var user = (CustomPrincipal)Session["LoggedUser"];
                _regNo = user.UserId;
            }
            
            var statement = _bursaryService.StudentAccountStatement(_regNo);
            return new ViewAsPdf(statement);
        }

        public ActionResult ViewStudentPayments()
        {
            return View();
        }

        public ActionResult ViewStudentPaymentsAsPDF(DateTime fromDate, DateTime toDate, string accountCode, string deptCode, string progType, string rpt)
        {
            FeesCollectionDTO dto = null;
            switch (rpt)
            {
                case "Other Fees":
                    dto = _bursaryService.StudentPayments(fromDate, toDate, accountCode, deptCode, progType);
                    break;
                case "School Fee":
                    dto = _bursaryService.SchoolFeePayments(fromDate, toDate, deptCode, progType);
                    break;
            }

            return new ViewAsPdf(dto)
            {
                PageSize = Size.A4,
                PageOrientation = Orientation.Portrait,

                CustomSwitches = "--footer-right \"Date: [date] [time]\" " +
                        "--footer-center \"Page: [page] of [toPage]\" --footer-line --footer-font-size \"9\" --footer-spacing 5 --footer-font-name \"calibri light\"",
                PageMargins = { Left = 2, Right = 2, Top = 1, Bottom = 2 }
            };
        }


        public ActionResult ViewStudentPaymentsAsExcel(DateTime fromDate, DateTime toDate, string accountCode, string deptCode, string progType, string rpt)
        {
            FeesCollectionDTO dto = null;
            switch (rpt)
            {
                case "Other Fees":
                    dto = _bursaryService.StudentPayments(fromDate, toDate, accountCode, deptCode, progType);
                    break;
                case "School Fee":
                    dto = _bursaryService.SchoolFeePayments(fromDate, toDate, deptCode,progType);
                    break;
                     
            }
            if (dto != null)
            {
                Export2Excel<FeesCollectionDetailsDTO>(dto.Details, dto.Title);
                return View("ViewStudentPayments");
            }
            else
            return View("ViewStudentPayments");

        }
        public ActionResult SchoolFeePayments()
        {
            return View();
        }
        public ActionResult ViewSchoolFeePaymentsAsPDF(int sessionId,string deptCode)
        {

            var payments = _bursaryService.SchoolFeePayments(sessionId,deptCode);

            return new ViewAsPdf(payments)
            {
                PageSize = Size.A4,
                PageOrientation = Orientation.Portrait,

                CustomSwitches = "--footer-right \"Date: [date] [time]\" " +
                        "--footer-center \"Page: [page] of [toPage]\" --footer-line --footer-font-size \"9\" --footer-spacing 5 --footer-font-name \"calibri light\"",
                PageMargins = { Left = 2, Right = 2, Top = 1, Bottom = 2 }
            };
        }


        public ActionResult ViewSchoolFeePaymentsAsExcel(int sessionId, string deptCode)
        {
            var payments = _bursaryService.SchoolFeePayments(sessionId, deptCode);
            if (payments != null)
            {
                Export2Excel<FeesCollectionDetailsDTO>(payments.Details, payments.Session + "-" + payments.Department);
            }

            return View();

        }

        public ActionResult CollectionSummary()
        {
            return View();
        }
        public JsonResult FetchCollectionSummary(DateTime from, DateTime to, string progType)
        {
            return Json(_bursaryService.FeesCollectionSummary(from, to, progType), JsonRequestBehavior.AllowGet);
        }
        #endregion
        #region POSTING OLD FEES FROM OLD PORTAL
        [KSWebAuthorisation]
        public ActionResult PostConfirmedOldSchoolFeePayment()
        {
            return View();
        }

        [KSWebAuthorisation]
        public string FetchConfirmedSchoolFeePaymentAmount(object[] data1)
        {
            int sessionId = (int)data1[0];
            int installment = (int)data1[1];
            int level = (int)data1[2];
            string matric = (string)data1[3];
            string flag;
            //Check if student is owing


            var schedule = _studentAccounts.GenerateExpectedSchoolFeesPayment(matric, sessionId, installment, level, out flag);
            outPutMsg result = new outPutMsg();
            result.message = flag;
            result.value = schedule;
            var chk = JsonConvert.SerializeObject(result);

            return chk;
        }
        [KSWebAuthorisation]
        public string SubmitConfirmedSchoolFeePayment(object[] data1)
        {
            int sessionId = (int)data1[0];
            int installmentId = (int)data1[1];

Eduplus.Web.SMC/Views/Bursary/AccountGroups.cshtml
@{
    ViewBag.Title = "Accounts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <h2>Accounts</h2>
    <hr />
    <p><a class="btn btn-success" data-bind="click:$root.add" href="#" title="edit"><i class="icon-plus"></i> Add Account</a></p>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                
                <th style="width: 120px; text-align:right;" />
            </tr>
        </thead>
        <tbody data-bind="template:{name:templateToUse, foreach:list}"></tbody>
        <tfoot>
            <tr><td><a class="btn btn-success" data-bind="click:$root.add" href="#" title="edit"><i class="icon-plus"></i> Add Account</a></td></tr>
        </tfoot>
    </table>

    
    <script id="itemsTmpl" type="text/html">
        <tr>
            <td data-bind="text:GroupId"></td>
            <td data-bind="text:Title"></td>
            
            <td class="buttons">
                <a class="btn btn-success" data-bind="click: $root.edit" href="#" title="edit"><i class="glyphicon glyphicon-edit"></i></a>

            </td>
        </tr>
    </script>

    <script id="editTmpl" type="text/html">
        <tr>
            <td></td>
            <td><input  type="text" data-bind="value:Title" class="form-control"/></td>
            
            
            <td><input type="checkbox" class="form-control" data-bind="checked:Active"/></td>
            <td class="buttons">
                <a class="btn btn-success" data-bind="click:$root.save" href="#" title="save"><i class="glyphicon glyphicon-floppy-disk"></i></a>
                <a class="btn btn-danger" data-bind="click: $root.cancel" href="#" title="cancel"><i class="glyphicon glyphicon-remove-sign"></i></a>
            </td>
        </tr>
    </script>  
</div>
@section Scripts{
    @Scripts.Render("~/Scripts/ViewModels/accountsGroupVM.js")
    }

Eduplus.Web.SMC/Views/Bursary/Accounts.cshtml
@{
    ViewBag.Title = "Accounts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <h2>Accounts</h2>
    <hr />
    <p><a class="btn btn-success" data-bind="click:$root.add" href="#" title="edit"><i class="icon-plus"></i> Add Account</a></p>
    <table class="table">
        <thead>
            <tr>
                <th>Code</th>
                <th>Title</th>
                <th>Description</th>
                <th>Act Type</th>
                <th>Op. Balance</th>
                <th>Cur. Balance</th>
                <th>IsActive</th>
                <th style="width: 120px; text-align:right;" />
            </tr>
        </thead>
        <tbody data-bind="template:{name:templateToUse, foreach:list}"></tbody>
        <tfoot>
            <tr><td><a class="btn btn-success" data-bind="click:$root.add" href="#" title="edit"><i class="icon-plus"></i> Add Account</a></td></tr>
        </tfoot>
    </table>
    <p><a class="btn btn-success" data-bind="click:$root.add" href="#" title="edit"><i class="icon-plus"></i> Add Account</a></p>
    
    <script id="itemsTmpl" type="text/html">
        <tr>
            <td data-bind="text:AccountCode"></td>
            <td data-bind="text:Title"></td>
            <td data-bind="text:Description"></td>
            <td data-bind="text:AccountType"></td>
            <td data-bind="text:OpeningBalance"></td>
            <td data-bind="text:CurrentBalance"></td>
            <td data-bind="text:Active"></td>
            <td class="buttons">
                <a class="btn btn-success" data-bind="click: $root.edit" href="#" title="edit"><i class="glyphicon glyphicon-edit"></i></a>

            </td>
        </tr>
    </script>

    <script id="editTmpl" type="text/html">
        <tr>
            <td><input class="form-control" data-bind="value:AccountCode"/></td>
            <td><input class="form-control" data-bind="value:Title"/></td>
            <td><input class="form-control" data-bind="value:Description"/></td>
            <td><select data-bind="value:AccountType,options:AccountTypes" class="form-control"></select></td>
            <td><input class="form-control" data-bind="value:OpeningBalance"/></td>
            <td><input class="form-control" data-bind="value:CurrentBalance"/></td>
            <td><input type="checkbox" class="form-control" data-bind="checked:Active"/></td>
            <td class="buttons">
                <a class="btn btn-success" data-bind="click:$root.save" href="#" title="save"><i class="glyphicon glyphicon-floppy-disk"></i></a>
                <a class="btn btn-danger" data-bind="click: $root.cancel" href="#" title="cancel"><i class="glyphicon glyphicon-remove-sign"></i></a>
            </td>
        </tr>
    </script>  
</div>
@section Scripts{
    @Scripts.Render("~/Scripts/ViewModels/accountsVM.js")
    }

Eduplus.Web.SMC/Views/Bursary/AddFeeSchedule.cshtml
@{
    ViewBag.Title = "AddFeeSchedule";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="col-md-11">
    <h3>Add Fee Schedule</h3>   
     
    <div class="row form-inline">
         
        <div class="form-group">
            <div class="col-md-3">
                <select data-bind="value:SessionId,options:Sessions,optionsValue:'SessionId',optionsText:'Title',optionsCaption:'--Session--'" class="form-control"></select>
                 
            </div>
            <div class="col-md-3">
                <select data-bind="value:ProgrammeType,options:progTypes,optionsValue:'Type',optionsText:'Type',optionsCaption:'Select Programme Type'" class="form-control"></select>
                 
            </div>
            <div class="col-md-4">
                <select data-bind="value:FacultyCode,options:Faculties,optionsValue:'FacultyCode',optionsText:'Faculty',optionsCaption:'-Select School'" class="form-control"></select>
                
            </div>
            
        </div>
         
        <div class="form-group">
            
        </div>
        
    </div>
    
    <hr />
    <h5>@Html.ActionLink("Click to go back to all schedules", "FeeSchedules")</h5>
    <table class="table table-responsive">
       <caption style="font-size:20px;font-weight:bold;background-color:#54b972">Schedule Details</caption>
        <thead>
            <tr>
                <th>Account</th>
                <th>Amount</th>
                <th>Type</th>
                <th>Applies To</th>
            </tr>
        </thead>
        <tbody data-bind="foreach:Details">
            <tr>
                <td><select data-bind="value:AccountCode,options:accounts,optionsValue:'AccountCode',optionsText:'Title',optionsCaption:'-Select Account'" class="form-control"></select></td>
                <td><input data-bind="value:Amount" class="form-control" /></td>
                <td><select data-bind="value:Type,options:types,optionsCaption:'Fee is...'" class="form-control"></select></td>
                <td><select data-bind="value:AppliesTo,options:applies,optionsCaption:'Fee is applicable to...'" class="form-control" /></td>
                <td class="buttons">
                    <a class="btn btn-danger" data-bind="click: $root.removeItem" href="#" title="edit"><i class="glyphicon glyphicon-remove">Remove</i></a>

                </td>
            </tr>
        </tbody>
        <tfoot>
            <tr> 
                <td class="button">
                    <a class="btn btn-success" data-bind="click:$root.addItem, disable:disableButton" href="#" title="save"><i class="glyphicon glyphicon-plus-sign">Add</i></a>
                    <img src="~/Content/images/wait24.gif" data-bind="visible:disableButton" alt="busy"/>
                </td>
                <td data-bind="text:totalAmount"></td>
            </tr>
        </tfoot>
    </table>
</div>

@Scripts.Render("/Scripts/ViewModels/newFeeScheduleVM.js")

Eduplus.Web.SMC/Views/Bursary/CollectionSummary.cshtml
@{
    ViewBag.Title = "Collection Summary";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-7">
    <div class="row">
        <table class="table table-borderless">
            <tr><td>From</td><td><input type="date" class="form-control" data-bind="value:from" /></td></tr>
            <tr><td>to</td><td><input type="date" class="form-control" data-bind="value:to" /></td></tr>
            <tr><td>Programme Type</td><td><select class="form-control" data-bind="value:pType,options:progs,optionsCaption:'--Select Type--'"></select></td></tr>
            <tr><td></td><td><button class="btn btn-info" data-bind="click:fetch,disable:biz">Fetch</button>
                             <img src="~/Content/images/wait24.gif" data-bind="visible:biz" />
                </td>
                
            </tr>
        </table>
    </div>
    <div class="row">

        <table class="table table-borderless table-sm">
            <thead>
                <tr>
                    <th>Account Code</th>
                    <th>Account</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody data-bind="foreach:pays">
                <tr>
                    <td data-bind="text:Name"></td>
                    <td data-bind="text:Particulars"></td>
                    <td data-bind="text:Amount"></td>
                </tr>
            </tbody>
            <tfoot><tr><td>Total</td><td></td><td data-bind="text:total"></td></tr></tfoot>
        </table>
        <div class="form-group">

        </div>
    </div>
</div>

<script src="~/Scripts/ViewModels/feesCollectionSumary.js"></script>

Eduplus.Web.SMC/Views/Bursary/CreditStudent.cshtml
@{
    ViewBag.Title = "Pay Fees";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Credit Student Account</h3>
<hr />
<div class="form-horizontal">
    <div class="form-group">

        <div class="col-md-6">
            <select data-bind="value:SessionId, options:sessions,optionsValue:'SessionId',optionsText:'Title', optionsCaption:'Select Session'" class="form-control"></select>
        </div>

    </div>
    <div class="form-group">

        <div class="col-md-12">
            <select data-bind="value:AccountCode, options:accounts,optionsValue:'AccountCode',optionsText:'Title', optionsCaption:'Select Account'" class="form-control"></select>
        </div>

    </div>

    <div class="form-group">
        <div class="col-md-6">
            <input type="text" data-bind="value:Amount" class="form-control" placeholder="Enter Amount" />
        </div>
    </div>

    
    <div class="form-group">
        <div class="col-md-6">
            <input type="text" data-bind="value:Particulars" class="form-control" placeholder="Particulars" />
        </div>
    </div>
    

    <div class="form-group">
        <div class="col-md-6">
            <button data-bind="click:submit,disable:Kill" class="btn btn-success">Generate Payment Invoice</button>
            <img src="~/Content/images/wait24.gif" data-bind="visible:Kill" />
        </div>
    </div>
</div>


@Scripts.Render("~/Scripts/ViewModels/creditStudentVM.js")

Eduplus.Web.SMC/Views/Bursary/DailyCollections.cshtml
@{
    ViewBag.Title = "Daily Collections";
}
<div>
@using (Html.BeginForm("DailyCollections", "Bursary", FormMethod.Post))
{ 
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row form-horizontal">
        <div class="form-group">
            From
            <div class="col-md-12">
                <input class="form-control" id="fromDate" name="fromDate" type="date" />
            </div>
        </div>
    </div>
    <div class="row form-horizontal">
        <div class="form-group">
            To
            <div class="col-md-12">
                <input class="form-control" id="toDate" name="toDate" type="date" />
            </div>
        </div>
       
    </div>

    <div class="row form-horizontal">
        <div class="form-group">
            Report Type
            <div class="col-md-12">
                <select class="form-control" id="rptType" name="rptType">
                    <option value="">--Report Type--</option>
                    <option value="Bulk">Bulk</option>
                    <option value="Full">Detailed</option>
                </select>
            </div>
        </div>

    </div>
    <div class="row form-horizontal">
        
        <div class="form-group">
            <input type="submit" class="btn btn-info" value="Submit" />
        </div>
    </div>
}
    </div>

Eduplus.Web.SMC/Views/Bursary/FeeSchedules.cshtml
@{
    ViewBag.Title = "FeeSchedules";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Fee Schedules</h3>
<hr/>
<p><a class="btn btn-success" data-bind="click:$root.add" href="#" title="edit"><i class="icon-plus"></i> Add Schedule</a></p>
<table class="table table-responsive table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Session</th>
            <th>Prog Type</th>
            <th>Faculty</th>
            <th>Total Amt</th>
            
            <th>Status</th>
        </tr>
    </thead>
    <tbody data-bind="foreach:Schedules">
        <tr>
            <td data-bind="text:ScheduleId"></td>
            <td data-bind="text:Session"></td>
            <td data-bind="text:ProgrammeType"></td>
            <td data-bind="text:Faculty"></td>
            <td data-bind="text:Total"></td>
            
            <td data-bind="text:Status"></td>
            <td class="buttons">
                <a class="btn btn-success" data-bind="click: $root.detail" href="#" title="edit"><i class="glyphicon glyphicon-new-window">Details</i></a>
            </td>
            <td class="buttons">
                <a class="btn btn-danger" data-bind="click: $root.apply, disabled:$root.dC" href="#" title="edit"><i class="glyphicon glyphicon-floppy-open">Apply</i></a>
                <img src="~/Content/images/wait24.gif" data-bind="visible:$root.dC" />
            </td>
        </tr>
    </tbody>
</table>
@section Scripts{
    @Scripts.Render("~/Scripts/ViewModels/feeSchedulesVM.js")
}

Eduplus.Web.SMC/Views/Bursary/FeesCollections.cshtml
@{
    ViewBag.Title = "FeesCollections";
}
<div class="col-md-8">
    <h2>Fees Collections Report Generation</h2>
    <select data-bind="value:duration,options:durations',optionsCaption:'Choose Duration'" class="form-control"></select>
    <select data-bind="value:rpt,options:reports',optionsCaption:'Choose Report'" class="form-control"></select>
    <select data-bind="visible:hideS,value:session,options:sessions,optionsValue:'Title',optionsText:'Title',optionsCaption:'Choose Session'" class="form-control"></select>
    <select data-bind="visible:hideS,value:session,options:sessions,optionsValue:'Title',optionsText:'Title',optionsCaption:'Choose Session'" class="form-control"></select>
    <select data-bind="visible:hideAct,value:account,options:accounts,optionsValue:'AccountCode',optionsText:'Title',optionsCaption:'Choose Account'" class="form-control"></select>

</div>
@section Scripts{
    @Scripts.Render("~/Scripts/ViewModels/FeesCollectionsVM.js")
}

Eduplus.Web.SMC/Views/Bursary/PostConfirmedOldSchoolFeePayment.cshtml
@{
    ViewBag.Title = "Schoo fee payment";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}
<div class="form-horizontal">
    <h3>Pay School Fee</h3>
    <hr />
     
    <div class="form-group">

        <div class="col-md-12">
            <select data-bind="value:sessionId, options:sessions,optionsValue:'SessionId',optionsText:'Title', optionsCaption:'Select Session'" class="form-control"></select>
        </div>

    </div>

    <div class="form-group">

        <div class="col-md-12">
            <select data-bind="value:installment, options:installments,optionsValue:'OptionsId',optionsText:'Installment', optionsCaption:'My Fee Payment Plan'" class="form-control"></select>
        </div>

    </div>
    <div class="form-group">
        <div class="col-md-12">
            <select data-bind="value:lvl, options:levels,optionsCaption:'Select Level to Pay'" class="form-control"></select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-12">
            <input data-bind="value:amtToPay" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3">
            <button data-bind="click:fetch, disable:kill" class="btn btn-success">Fetch Amount</button>
            <img src="~/Content/images/wait24.gif" data-bind="visible:kill" />
        </div>
        
    </div>

    <div class="form-group">
        <div class="col-md-3">
            <button data-bind="click:submit, disable:kill" class="btn btn-success">Submit</button>
            <img src="~/Content/images/wait24.gif" data-bind="visible:kill" />
        </div>

    </div>

</div>
    
@Scripts.Render("~/Scripts/ViewModels/postConfirmedschoolFeePaymentVM.js")

Eduplus.Web.SMC/Views/Bursary/SessionCollectionsSummary.cshtml
@model IEnumerable<Eduplos.DTO.BursaryModule.AccountsDTO>
@{
    ViewBag.Title = "SessionCollections";
    Layout = "~/Views/Shared/_A4ReportLayout.cshtml";
}
@if(Model.Count()==0)
{
    <h4>Oops no records found</h4>
}
else
{
    <h4> Session Fees Collection</h4>
    <p>Session: @ViewBag.sess</p>
    <table class="table table-responsive">
        <thead style="display: table-row-group">
            <tr>
                <th>S/N</th>
                <th>Code</th>
                <th>Account</th>
                <th>Amount{N}</th>
            </tr>
        </thead>
        <tbody>
            @{
                int sno = 0;
            }
            @foreach(var i in Model)
            {
                <tr>
                    <td>
                        @{ sno++; }
                    @sno
                </td>
                    <td style="text-align:center">@Html.DisplayFor(a=>i.AccountCode)</td>
                    <td>@Html.DisplayFor(a => i.Title)</td>
                    <td style="text-align:right">@string.Format("{0:#,##0.00;(#,##0.00)}", i.Amount)</td>
                    
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td></td>
                <td></td>
                <td>Total</td>
                <td style="text-align:right">@string.Format("{0:#,##0.00;(#,##0.00)}", Model.Sum(a=>a.Amount))</td>
            </tr>
        </tfoot>
    </table>
}

Eduplus.Web.SMC/Views/Bursary/ViewSchoolFeePaymentsAsExcel.cshtml
@{
    ViewBag.Title = "ViewSchoolFeePaymentsAsExcel";
}

<h2>Oops no record found</h2>

Eduplus.Web.SMC/Views/Bursary/ViewSchoolFeePaymentsAsPDF.cshtml
@model Eduplos.DTO.BursaryModule.FeesCollectionDTO
@{
    ViewBag.Title = "Student Payments";
    Layout = "~/Views/Shared/_A4ReportLayout.cshtml";
}
@if(Model==null)
{
    <h4>Oops no records found</h4>
}
else
{
    <div>
        <h3>@Model.Title Payments</h3>
        <p>
            
            Department:  @Model.Department;
        </p>

        <table class="table table-responsive table-hover">
            <thead style="display: table-row-group">
                <tr>
                    <th>S/N</th>
                    <th>RegNo</th>
                    <th>Name</th>
                    <th>Programme</th>
                    <th>Level</th>
                     
                    <th>TransRef</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                @{
                    int sno = 0;
                }
                @foreach (var p in Model.Details)
                {

                    <tr>
                        <td>
                            @{ sno++; }
                        @sno
                    </td>
                    <td>@Html.DisplayFor(a => p.RegNo)</td>
                    <td>@Html.DisplayFor(a => p.Name)</td>
                    <td>@Html.DisplayFor(a => p.Programme)</td>
                        <td>@Html.DisplayFor(a => p.Level)</td>
                         
                        <td>@Html.DisplayFor(a => p.TransRef)</td>
                         
                    <td style="text-align:right">@string.Format("{0:#,##0.00;(#,##0.00)}", p.Amount)</td>
                </tr>
                            }
            </tbody>
            <tfoot>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>Total</td>
                    <td></td>
                     
                    <td></td>
                    <td style="text-align:right">
                        @string.Format("{0:#,##0.00;(#,##0.00)}", Model.Total)
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
                            }